version: '3.4'

services:
  multitenantgateway.api:
    image: ${DOCKER_REGISTRY-}multitenantgatewayapi
    build:
      context: .
      dockerfile: src/ApiGateway/MultitenantGateway.Api/Dockerfile

  demoauth.api:
    image: ${DOCKER_REGISTRY-}demoauthapi
    build:
      context: .
      dockerfile: src/MicroAutenticathion/DemoAuth.Api/Dockerfile

  multitenant:
    image: ${DOCKER_REGISTRY-}multitenant
    build:
      context: .
      dockerfile: src/MicroMultitenant/Multitenant/Dockerfile

  redis:
    image: redis:7.2.4
    container_name: redis_service

  postgres:
    image: postgres:16.2
    container_name: postgres_db

  rabbitmq:
    image: rabbitmq:3.13.0-rc.5-management
    container_name: rabbitmq_service

networks:
  default:
    external:
      name: multitenantnet
